### ISSUE TITLE
amap or umap?

### ISSUE THREAD

**Issue by fegarcia-bcam** [swansonk14/p_tqdm#17]
Thanks for your repository, it's a nice and useful work.

Sorry if this issue is trivial, but I'm a newbie with parallel processing.
I just managed to parallelize my code with Pathos and was searching for a progress bar, when I found p_tqdm.

My code currently uses Pathos' amap (asynchronous)
[https://pathos.readthedocs.io/en/latest/pathos.html#pathos.multiprocessing.ProcessPool.amap](https://pathos.readthedocs.io/en/latest/pathos.html#pathos.multiprocessing.ProcessPool.amap)
.. which does not seem to be supported in your work, but instead umap (unordered). Or are they equivalent? Would you perhaps be so kind to extend your library?

Thank you in advance

**Comment by swansonk14** [comment]
Hi @fegarcia-bcam, thank you for using `p_tqdm` and for raising the issue! I actually wasn't aware of Pathos' `amap` before (thank you for bringing it to my attention!). After reading through I think there are some important  differences between `amap` and `umap`:

`umap`: Iterates over the elements of the lists in an arbitrary order. Is blocking, meaning Python will not execute the next line of code until the map is complete.

`amap`: Iterates over the elements of the lists in the provided order. Is not blocking, meaning Python will start executing the next line of code even before the map is complete. This is accomplished by returning a `MapResult` object from which you can extract the results (when they're done) using `.get()` rather than simply returning a list of results as `umap` does.

I would add `amap` to `p_tqdm` if possible, but I did some experimentation and it doesn't seem like that's possible due to the asynchronous nature of `amap`, as described below. If you need the asynchronous behavior, then unfortunately you're going to be stuck using `amap` without a `tqdm` progress bar. However, if the asynchronous behavior is not necessary, then you can either use `p_tqdm`'s `p_umap` for an unordered map or `p_map` for an ordered map with a progress bar.

The problem with `amap` is that it returns a `MapResult` object rather than an iterator over the results. This object has a `.ready()` method that lets you check whether the asynchronous application of the function is complete and a `.get()` method that lets you get the results once they're done, but there doesn't seem to be a way to access the intermediate results, which is necessary for `tqdm` to generate a progress bar.

Specifically, when I wrap the `amap` call in a `tqdm`, like this:
```python
import time
from tqdm import tqdm
from pathos.multiprocessing import ProcessPool as Pool

def f(x, y):
    time.sleep(1)
    return x + y

a = b = list(range(100))

for x in tqdm(Pool().amap(f, a, b).get(), total=len(a)):
    print(x)
```
then the tqdm progress bar does nothing for a long time until it suddenly jumps to 100% once the `amap` is complete and the result is available.

Furthermore, the following:
```python
for x in tqdm(Pool().amap(f, a, b), total=len(a)):
    print(x)
```
is not valid since leaving out the `.get()` returns a `MapResult` object which is not iterable.

Alternatively, I tried:
```python
for x in Pool().amap(f, tqdm(a), b).get():
    print(x)
```
but in this case I get the opposite problem, where the tqdm instantly jumps to 100% (apparently all of `a` is consumed immediately by the `amap`, even though the elements of `a` are used over time).

So unfortunately it doesn't seem like there's a way for the `tqdm` to capture the internal iteration of the `amap` call.

**Comment by fegarcia-bcam** [comment]
Wow, @swansonk14, that's a quick, clear and exhaustive response! Extremely appreciated.

Now that I've read your explanation, I understand that I don't really need the asynchronous behaviour. I had just picked `amap` as a newbie, after a quick read of Pathos options: it seemed to me like the one making the most out of the computational resources.

I think I've got your point, and given the structure of my later code extracting the results, probably the simplest and most elegant in my case is an iterative solution, either `imap` or `uimap`.

Thanks a lot!
