### ISSUE TITLE
PicklingError: Can't pickle 'tkapp' object: <tkapp object at 0x000000000B66C930>

### ISSUE THREAD

**Issue by forkozi** [swansonk14/p_tqdm#3]
Hi.  I was excited to find your package for making a progress bar work with pathos multiprocessing.    When I change my original code..
```
p = pp.ProcessPool(4)
p.map(method, generator)
p.close()
p.join()
```
to
```
p_map(method, generator)
```
I get the following error:

PicklingError: Can't pickle 'tkapp' object: <tkapp object at 0x000000000B66C930>

Should p_tqdm work with Tk objects?

Thanks,
Nick

**Comment by forkozi** [comment]
In other scenarios, I get an error saying it can't pickle generators.  It seems as though perhaps p_tqdm is using the native multiprocessing package and not pathos.  Is there something I need to do to tell p_tqdm to use pathos?

**Comment by swansonk14** [comment]
Hmm, p_tqdm should be using pathos since the import is `from pathos.multiprocessing import ProcessingPool as Pool`. Can you provide a more complete example where you define `method` and `generator` so I can see the issue for myself? (Also sorry for not seeing this earlier! I wasn't maintaining the library for a while but I'm hoping to be more active now.)
